# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "sml report"
author: Nicole Rosi & Jens Peter Schøler
logo: logo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force    # See https://jupyterbook.org/content/execute.html
  timeout: -1                 # see https://jupyterbook.org/en/stable/content/execute.html#the-execution-working-directory
  allow_errors: true          # Allow errors during execution
  raise_on_error: false       # Do not raise an error if a notebook fails

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # Math extension
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

html_theme_options:
  extra_footer: |
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" async></script>

# Add a bibtex file so that we can create citations <-- not working currently
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  branch: main #master  # Which branch of the repository should be used when creating links (optional)
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
