name: jupybook
channels:
  - defaults
dependencies:
  # Conda packages
  - absl-py==1.4.0
  - asttokens==2.0.5
  - astunparse==1.6.3
  - attrs==23.1.0
  - bottleneck==1.3.5
  - brotli==1.0.9
  - brotli-bin==1.0.9
  - brotlipy==0.7.0
  - bzip2==1.0.8
  - ca-certificates==2023.01.10
  - cachetools==5.5.0
  - certifi==2022.12.7
  - cffi==1.15.1
  - charset-normalizer==2.0.4
  - cmake==3.30.2
  - colorama==0.4.6
  - comm==0.1.2
  - contourpy==1.0.5
  #- cpuonly==2.0
  - cryptography==38.0.4
  - cycler==0.11.0
  - debugpy==1.5.1
  - decorator==5.1.1
  - entrypoints==0.4
  - executing==0.8.3
  - ffmpeg==5.1.2
  - fftw==3.3.9
  - fonttools==4.25.0
  - freetype==2.12.1
  - glib==2.69.1
  #- icc_rt==2022.1.0
  - icu==58.2
  - idna==3.4
  - importlib-metadata==6.0.0
  - importlib_resources==6.4.3
  - intel-openmp==2021.4.0
  - ipykernel==6.19.2
  - ipympl==0.9.4
  - ipython==8.8.0
  - ipython_genutils==0.2.0
  - ipywidgets==8.0.4
  - jedi==0.18.1
  - jpeg==9e
  - jsonschema==4.17.3
  - jupyter_client==7.4.8
  - jupyter_core==5.1.1
  - jupyterlab_widgets==3.0.5
  - kiwisolver==1.4.4
  - lerc==3.0
  - libbrotlicommon==1.0.9
  - libbrotlidec==1.0.9
  - libbrotlienc==1.0.9
  - libclang==14.0.6
  - libdeflate==1.8
  - libffi==3.3
  - libiconv==1.16
  - libogg==1.3.5
  - libpng==1.6.37
  - libsodium==1.0.18
  - libtiff==4.5.0
  - libuv==1.40.0
  - libvorbis==1.3.7
  - libwebp==1.2.4
  - libwebp-base==1.2.4
  - libxml2==2.9.14
  - libxslt==1.1.35
  - lz4-c==1.9.4
  - markdown==3.4.1
  - markupsafe==2.1.5
  - matplotlib==3.6.2
  - matplotlib-base==3.6.2
  - matplotlib-inline==0.1.6
  - mkl==2021.4.0
  - mkl-service==2.4.0
  - mkl_fft==1.3.1
  - mkl_random==1.2.2
  - mpmath==1.2.1
  - munkres==1.1.4
  - nbformat==5.10.4
  - nest-asyncio==1.5.6
  - numexpr==2.8.4
  - numpy==1.23.5
  - numpy-base==1.23.5
  - openssl==1.1.1t
  - opt-einsum==3.3.0
  - packaging==22.0
  - pandas==1.5.2
  - parso==0.8.3
  - pcre==8.45
  - pickleshare==0.7.5
  - pillow==9.3.0
  - pip==22.3.1
  - pkgutil-resolve-name==1.3.10
  - platformdirs==2.5.2
  - ply==3.11
  - prompt-toolkit==3.0.36
  - protobuf==3.20.3
  - psutil==5.9.0
  - pure_eval==0.2.2
  - pyaml==21.10.1
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pycparser==2.21
  - pydmd==1.0.0 
  - pygments==2.11.2
  - pyopenssl==22.0.0
  - pyparsing==3.0.9
  - pyqt==5.15.7
  - pyqt5-sip==12.11.0
  - pyrsistent==0.18.0
  - pysocks==1.7.1
  - python==3.10 
  - python-dateutil==2.8.2
  - python-fastjsonschema==2.16.2
  - pytorch==1.13.1
  #- pytorch-mutex==1.0
  - pytz==2022.7
  - pywin32==306
  - pyyaml==6.0
  - pyzmq==23.2.0
  - qt-main==5.15.2
  - qt-webengine==5.15.9
  - qtwebkit==5.212
  - requests==2.28.1
  - requests-oauthlib==2.0.0
  - rsa==4.9
  - scikit-learn==1.5.1
  - scikit-optimize==0.9.0
  - scipy==1.9.3
  - setuptools==65.6.3
  - pysindy==1.7.5
  - sip==6.6.2
  - six==1.16.0
  #- sparsereg==0.10.0
  #- sqlite==3.40.1
  - stack_data==0.2.0
  - sympy==1.11.1
  #- tensorboard==2.11.2
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorflow==2.9.1 
  - tensorflow-base==2.9.1
  #- tensorflow-addons==0.19.0
  - tensorflow-estimator==2.9.1
  #- tensorflow-intel==2.11.0
  #- tensorflow-io-gcs-filesystem==0.30.0
  #- termcolor==2.2.0
  #- threadpoolctl==3.1.0
  - tk==8.6.12
  - toml==0.10.2
  - toolz==0.12.0
  #- torchaudio==0.13.1
  #- torchvision==0.14.1
  - tornado==6.2
  - tqdm==4.64.1
  - traitlets==5.7.1
  - typeguard==2.13.3
  - typing_extensions==4.4.0
  - tzdata==2022g
  - urllib3==1.26.14
  #- vc==14.2
  #- vs2015_runtime==14.27.29016
  - wcwidth==0.2.5
  - werkzeug==2.2.2
  - wheel==0.37.1
  - widgetsnbextension==4.0.5
  #- win_inet_pton==1.1.0
  #- wincertstore==0.2
  - wrapt==1.14.1
  - xz==5.2.10
  - zeromq==4.3.4
  #- zipp==3.12.1
  - zlib==1.2.13
  - zstd==1.5.2
  - pip:
    - joblib==1.2.0
